name: Dependency Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for outdated packages
      run: npm outdated
      
    - name: Update dependencies
      run: |
        npm update
        npm audit fix
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Automated dependency update'
        body: |
          ## 🔄 Automated Dependency Update
          
          This PR was automatically created to update outdated dependencies.
          
          ### Changes Made:
          - Updated npm packages to latest compatible versions
          - Applied security fixes where possible
          
          ### To Review:
          - [ ] Test the application locally
          - [ ] Verify all functionality works as expected
          - [ ] Check for any breaking changes
          
          ### Manual Steps Required:
          - Review and test the changes
          - Merge if everything looks good
          
          ---
          *This PR was created automatically by GitHub Actions*
        branch: dependency-update/$(date +%Y%m%d)
        delete-branch: true
